### ISSUE TITLE
Disable forced injection of bootstrap/popper/jquery

### ISSUE THREAD

**Issue by cbichis** [jield-webdev/laminas-bootstrap5#1]
Hi,

It should be a way to disable forced injection of bootstrap/popper/jquery.

It would create more problems than benefits in certain cases.

**Comment by japaveh** [comment]
I suggest to create a setting where the injection can be overruled and omitted. Then you can disable this for your project.

**Comment by japaveh** [comment]
It is now possible to avoid loading the dependencies:
Check this file for more details

https://github.com/jield-webdev/laminas-bootstrap5/blob/main/config/laminas-bootstrap5.local.php.dist

**Comment by cbichis** [comment]
Great!
